### ISSUE TITLE
unauthorized: You are not a db or server admin.

### ISSUE THREAD

**Issue by rmshkmr** [pin3da/passport-couchdb#1]
No functions found for **User.find()**

**ERROR**
unauthorized: You are not a db or server admin.

undefined
```

CouchError: unauthorized: You are not a db or server admin.
    at Request._onResponse [as _callback] (/home/ramesh/Documents/Learning/passport-couchdb-master/node_modules/cradle/lib/cradle.js:232:29)
    at Request.self.callback (/home/ramesh/Documents/Learning/passport-couchdb-master/node_modules/request/request.js:188:22)
    at emitTwo (events.js:87:13)
    at Request.emit (events.js:172:7)
    at Request.<anonymous> (/home/ramesh/Documents/Learning/passport-couchdb-master/node_modules/request/request.js:1171:10)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at IncomingMessage.<anonymous> (/home/ramesh/Documents/Learning/passport-couchdb-master/node_modules/request/request.js:1091:12)
    at IncomingMessage.g (events.js:260:16)
    at emitNone (events.js:72:20)
```

**Comment by justinlawrence** [comment]
Sounds like a permission issue. I think you need to add your user and password to config/development.js.

**Comment by shikherwalia** [comment]
it is not working  (development.js)

**Comment by alexandergantikow** [comment]
Indeed, this looks like a permission issue. However, even if I specify the correct configuration details of the database, I get the above error. It looks to me more like the username and password are not being passed through properly. It looks like the 'resourceful' package uses 'cradle'. My skills are not sufficient to debug their interrelationships.
